### PR TITLE
ci: Add job to test `CMAKE_UNITY_BUILD`.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by Dekker1** [comment]
Should this be a seperate job. What are the downsides of using the unity build feature? Can we not just enable this feature for anyone building with CMake 3.16+?

**Comment by waywardmonkeys** [comment]
It isn't really something that you'd do for development or normal builds... I am (currently) using it when I do the build from Rust to keep the compile times down. (But I've also since upgraded to an M3 Max laptop which is incredibly fast...)

**Comment by Dekker1** [comment]
If it's not something that is generally applicable, then I'm not sure whether it is worthwhile adding the to the Chuffed CI. I don't think that the compatibility with the unity build feature would require a build for every push and pull request within chuffed.

**Comment by waywardmonkeys** [comment]
Sounds okay to me.

**Pull request closed without merging**
