### PR TITLE
Fix `chuffed-config.cmake.in`

### PR DESCRIPTION
**Pull request by LebedevRI**
While it (correctly!) deals with relative (instead of absolute) paths, there still is a problem: it assumes that `${CMAKE_CURRENT_LIST_DIR}` is `<???>/usr/lib/cmake/chuffed/`, but in e.g. debian it's actually `<???>/usr/lib/x86_64-linux-gnu/cmake/chuffed/`,
which requires 4, not 3, `cd ..`.

Fix that by computing the relative path at CMake time, oh, and avoid using `CMAKE_INSTALL_INCLUDEDIR` et al that may be different when the config is consumed...

### CODE REVIEW

**Comment by LebedevRI** [comment]
While there, a question:
1. Is there some test suite other than 
https://github.com/chuffed/chuffed/blob/2e67c74ea7084cf24ab42d8c08db3fac31bdf3ea/CMakeLists.txt#L261 ?
2. Is it intentional that these examples aren't plugged into `add_test()` ?
    (yes, i can see that they do not verify their own output...)

**Comment by Dekker1** [comment]
We never considered the usage of the CMake `add_test` functionality. I didn't know about it, but also (as you say) because the examples are certainly not a regular test suite. Most of the examples will require some type of input, they cannot just be run by themselves.

**Comment by LebedevRI** [comment]
... and the first question?

> 1. Is there some test suite other than

**Comment by Dekker1** [comment]
No, Chuffed currently relies on the MiniZinc compiler test suite and runs in the MiniZinc challenge to discover any problems.

This is unlikely to change, since chuffed is maintained, but not actively being developed.

**Comment by LebedevRI** [comment]
> No, Chuffed currently relies on the MiniZinc compiler test suite and runs in the MiniZinc challenge to discover any problems.

Oh. :/

**Pull request merged**
